kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: spire-demo
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.240.0.0/16"
  serviceSubnet: "10.241.0.0/16"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32000  # OIDC service port
        hostPort: 8080       # Host port for OIDC
        protocol: TCP
    extraMounts:
      - hostPath: ./config
        containerPath: /opt/spire/config
        readOnly: true
      - hostPath: ./data
        containerPath: /opt/spire/data
        readOnly: false
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
  - role: worker