apiVersion: v1
kind: Service
metadata:
  name: spire-oidc
  namespace: spire-oidc
spec:
  type: NodePort
  selector:
    app: spire-oidc-provider
  ports:
    - name: http
      port: 8080
      targetPort: spire-oidc-port
      nodePort: 32000