version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
      - "8201:8201"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=https://127.0.0.1:8200
      - VAULT_SKIP_VERIFY=true
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config:/vault/config
      - ./data:/vault/data
      - ./certs:/vault/certs
    command: server -dev -dev-tls -dev-root-token-id="root"
    networks:
      - vault-network
      - kind
    healthcheck:
      test: ["CMD", "vault", "status", "-tls-skip-verify"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  vault-network:
  kind:
    external: true